"use client";
import { useState, type FormEvent } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import PageTitle from "@/components/admin/page-title";
import { getCampaigns, saveCampaign, type Campaign } from "@/services/agent-setup";
import { apiErrorMessage } from "@/lib/api-error";

const empty: Omit<Campaign, "id"> = { brand_id: 0, affiliate_product_id: null, name: "", brief: "", priority: 50, monthly_target: 10, starts_on: null, ends_on: null, enabled: true };
export default function Page() {
  const q = useQuery({ queryKey: ["agent-campaigns"], queryFn: getCampaigns }); const client = useQueryClient();
  const [form, setForm] = useState(empty); const [id, setId] = useState<number | undefined>();
  async function submit(e: FormEvent) { e.preventDefault(); try { await saveCampaign(form, id); toast.success("Campaign saved."); setId(undefined); setForm(empty); await client.invalidateQueries({ queryKey: ["agent-campaigns"] }); } catch (err) { toast.error(apiErrorMessage(err, "Could not save campaign.")); } }
  return <><PageTitle title="Campaigns" description="Prioritize active campaigns up to their monthly target while the planner keeps the configured content mix." />
    <form onSubmit={submit} className="mb-6 grid gap-3 rounded-lg border bg-background p-4 sm:grid-cols-2"><label>Brand ID<input className="w-full rounded border p-2" type="number" min="1" required value={form.brand_id || ""} onChange={e => setForm({ ...form, brand_id: Number(e.target.value) })} /></label><label>Product ID (optional)<input className="w-full rounded border p-2" type="number" min="1" value={form.affiliate_product_id || ""} onChange={e => setForm({ ...form, affiliate_product_id: e.target.value ? Number(e.target.value) : null })} /></label><label>Name<input className="w-full rounded border p-2" required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label>Priority 0–100<input className="w-full rounded border p-2" type="number" min="0" max="100" value={form.priority} onChange={e => setForm({ ...form, priority: Number(e.target.value) })} /></label><label>Monthly target<input className="w-full rounded border p-2" type="number" min="1" max="120" value={form.monthly_target} onChange={e => setForm({ ...form, monthly_target: Number(e.target.value) })} /></label><label>Start / end dates<input className="w-full rounded border p-2" type="date" value={form.starts_on?.slice(0, 10) || ""} onChange={e => setForm({ ...form, starts_on: e.target.value || null })} /><input className="mt-2 w-full rounded border p-2" type="date" value={form.ends_on?.slice(0, 10) || ""} onChange={e => setForm({ ...form, ends_on: e.target.value || null })} /></label><label className="sm:col-span-2">Campaign brief (admin-approved facts and intent)<textarea className="w-full rounded border p-2" required value={form.brief} onChange={e => setForm({ ...form, brief: e.target.value })} /></label><label><input type="checkbox" checked={form.enabled} onChange={e => setForm({ ...form, enabled: e.target.checked })} /> Enabled</label><button className="rounded bg-primary px-4 py-2 text-primary-foreground" type="submit">{id ? "Update" : "Add"} campaign</button></form>
    {q.isPending && <p>Loading campaigns…</p>}{q.isError && <p role="alert">Could not load campaigns.</p>}
    <div className="space-y-3">{q.data?.map(c => <article className="rounded-lg border bg-background p-4" key={c.id}><strong>{c.name}</strong> · brand #{c.brand_id} · priority {c.priority} · {c.enabled ? "enabled" : "disabled"}<p className="whitespace-pre-wrap text-sm">{c.brief}</p><p className="text-sm">Target: {c.monthly_target}/month</p><button className="mt-2 underline" onClick={() => { setId(c.id); setForm({ brand_id: c.brand_id, affiliate_product_id: c.affiliate_product_id, name: c.name, brief: c.brief, priority: c.priority, monthly_target: c.monthly_target, starts_on: c.starts_on, ends_on: c.ends_on, enabled: c.enabled }); window.scrollTo({ top: 0, behavior: "smooth" }); }}>Edit</button></article>)}</div>
  </>;
}
