import api from "@/lib/axios";
import type { ApiResponse } from "@/types/api";

const root = "/admin/affiliate-agent";
export type Source = { id: number; brand_id: number; name: string; type: string; url: string | null; notes: string | null; allowed_domains: string[] | null; enabled: boolean; status: string; sync_is_stale: boolean; last_error: string | null; last_tested_at: string | null; last_test_status: string | null; last_test_error: string | null; last_synced_at: string | null; next_sync_at: string | null; sync_started_at: string | null; last_sync_failed_at: string | null; last_http_status: number | null; documents: { id: number; title: string; body: string; status: string; source_url: string; synced_at: string }[]; runs: { id: number; status: string; error: string | null; started_at: string; finished_at: string | null; http_status: number | null; content_changed: boolean | null; extracted_items: number; metadata: Record<string, unknown> | null }[] };
export type Campaign = { id: number; brand_id: number; affiliate_product_id: number | null; name: string; brief: string; priority: number; monthly_target: number; starts_on: string | null; ends_on: string | null; enabled: boolean };
export const getCampaigns = async () => (await api.get<ApiResponse<Campaign[]>>(`${root}/campaigns`)).data.data;
export const saveCampaign = async (data: Omit<Campaign, "id">, id?: number) => (await (id ? api.put(`${root}/campaigns/${id}`, data) : api.post(`${root}/campaigns`, data))).data.data;
export type SocialAccount = { id: number; platform: string; name: string; username: string | null; external_id: string; status: string; api_review_status: string; publishing_enabled: boolean; expires_at: string | null; last_verified_at: string | null; scopes: string[] | null; last_error: string | null; metadata: Record<string, string> | null };
export type AgentSetting = { timezone: string; videos_per_day: number; generation_time: string; generation_days: number[]; horizon_days: number; duration_seconds: number; default_voice_id: string | null; mix: Record<string, number>; publishing_slots: string[]; enabled_brand_ids: number[] | null; enabled_campaign_ids: number[] | null; generation_enabled: boolean; publishing_enabled: boolean; late_policy: string };
export type SetupData = { openai: boolean; elevenlabs: boolean; providers: Record<string, { status: string }>; sources: number; brands: { id: number; brand: { name: string }; name: string; status: string; last_synced_at: string | null; last_error: string | null }[]; accounts: SocialAccount[]; social_configured: Record<string, boolean>; settings: AgentSetting; infrastructure: { ffmpeg: string; storage: string; queue: string; queue_driver: string; scheduler: string; last_tick: string | null; redis: { status: string; message?: string } }; next_generation_run: string | null };
export const getSetup = async () => (await api.get<ApiResponse<SetupData>>(`${root}/setup`)).data.data;
export const getSources = async () => (await api.get<ApiResponse<Source[]>>(`${root}/sources`)).data.data;
export const saveSource = async (data: Record<string, unknown>, id?: number) => (await (id ? api.put(`${root}/sources/${id}`, data) : api.post(`${root}/sources`, data))).data.data;
export const sourceAction = async (id: number, action: "test" | "sync") => (await api.post<ApiResponse<{ ok: boolean; message?: string; source: Source }>>(`${root}/sources/${id}/${action}`)).data.data;
export const approveSourceDocument = async (id: number) => (await api.post(`${root}/source-documents/${id}/approve`)).data.data;
export const importSourceCsv = async (id: number, file: File) => { const form = new FormData(); form.append("file", file); return (await api.post(`${root}/sources/${id}/csv`, form)).data.data; };
export const getSocialAccounts = async () => (await api.get<ApiResponse<{ accounts: SocialAccount[]; configured: Record<string, boolean> }>>(`${root}/social-accounts`)).data.data;
export const connectSocial = async (platform: string) => (await api.post<ApiResponse<{ authorization_url: string }>>(`${root}/social-accounts/${platform}/connect`)).data.data;
export const updateSocial = async (id: number, data: Record<string, unknown>) => (await api.put(`${root}/social-accounts/${id}`, data)).data.data;
export const disconnectSocial = async (id: number) => (await api.delete(`${root}/social-accounts/${id}`)).data.data;
export const testSocial = async (id: number) => (await api.post<ApiResponse<{ ok: boolean; message: string }>>(`${root}/social-accounts/${id}/test`)).data.data;
export type PinterestOption = { id: string; name: string };
export type PinterestDestination = { id: number; scope_type: string; scope_id: number; external_board_id: string; external_board_name: string; external_section_id: string | null; external_section_name: string | null };
export const getPinterestBoards = async (id: number) => (await api.get<ApiResponse<{ items: PinterestOption[]; bookmark: string | null }>>(`${root}/social-accounts/${id}/boards`)).data.data;
export const getPinterestSections = async (id: number, board: string) => (await api.get<ApiResponse<{ items: PinterestOption[]; bookmark: string | null }>>(`${root}/social-accounts/${id}/boards/${board}/sections`)).data.data;
export const createPinterestBoard = async (id: number, name: string) => (await api.post(`${root}/social-accounts/${id}/boards`, { name })).data.data;
export const createPinterestSection = async (id: number, board: string, name: string) => (await api.post(`${root}/social-accounts/${id}/boards/${board}/sections`, { name })).data.data;
export const getPinterestDestinations = async (id: number) => (await api.get<ApiResponse<PinterestDestination[]>>(`${root}/social-accounts/${id}/destinations`)).data.data;
export const savePinterestDestination = async (id: number, data: { scope_type: string; scope_id: number | null; external_board_id: string; external_section_id: string | null }) => (await api.put(`${root}/social-accounts/${id}/destinations`, data)).data.data;
export const getAgentSettings = async () => (await api.get<ApiResponse<AgentSetting>>(`${root}/settings`)).data.data;
export const saveAgentSettings = async (data: AgentSetting) => (await api.put(`${root}/settings`, data)).data.data;
export const testAgentProvider = async (provider: string) => (await api.get<ApiResponse<{ ok: boolean; message: string }>>(`${root}/tests/${provider}`)).data.data;
export const getAgentVoices = async () => (await api.get<ApiResponse<{ voice_id: string; name: string; preview_url: string | null }[]>>(`${root}/voices`)).data.data;
export type PublicationRow = { id: number; version_id: number; platform: string; mode: string; status: string; scheduled_at: string; published_at: string | null; platform_url: string | null; external_id: string | null; error: string | null; content: { id: number; title: string } | null; account: { id: number; name: string } | null };
export const getAgentPublications = async () => (await api.get<ApiResponse<{ data: PublicationRow[] }>>(`${root}/publications`)).data.data;
export type CalendarContent = { id: number; title: string; status: string; planned_for: string | null; created_at: string };
export type CalendarPublication = PublicationRow & { content_id: number };
export const getAgentCalendar = async (from: string, to: string) => (await api.get<ApiResponse<{ contents: CalendarContent[]; publications: CalendarPublication[] }>>(`${root}/calendar`, { params: { from, to } })).data.data;
export type PublishingContent = { id: number; title: string; status: string; current_version_id: number | null; final_approved_version_id: number | null; publications: PublicationRow[] };
export const getPublishingDashboard = async () => (await api.get<ApiResponse<PublishingContent[]>>(`${root}/publishing`)).data.data;
