"use client";
import { useState, type FormEvent } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import PageTitle from "@/components/admin/page-title";
import { getSources, saveSource, sourceAction, approveSourceDocument, importSourceCsv, type Source } from "@/services/agent-setup";
import { apiErrorMessage } from "@/lib/api-error";

const types = ["OFFICIAL_WEBSITE", "OFFICIAL_DOCS", "API", "RSS_OR_FEED", "MANUAL", "CSV_IMPORT", "WEBHOOK"];
export default function Page() {
  const client = useQueryClient(); const q = useQuery({ queryKey: ["agent-sources"], queryFn: getSources });
  const [form, setForm] = useState({ id: 0, brand_id: "", name: "", type: "OFFICIAL_WEBSITE", url: "", notes: "", allowed_domains: "", enabled: true });
  const refresh = () => client.invalidateQueries({ queryKey: ["agent-sources"] });
  async function run(task: () => Promise<unknown>, message: string) { try { await task(); toast.success(message); await refresh(); } catch (e) { toast.error(apiErrorMessage(e, "Action failed.")); } }
  function edit(s: Source) { setForm({ id: s.id, brand_id: String(s.brand_id), name: s.name, type: s.type, url: s.url || "", notes: s.notes || "", allowed_domains: (s.allowed_domains || []).join(", "), enabled: s.enabled }); }
  function submit(e: FormEvent) { e.preventDefault(); void run(() => saveSource({ brand_id: Number(form.brand_id), name: form.name, type: form.type, url: form.url || null, notes: form.notes, allowed_domains: form.allowed_domains.split(",").map(x => x.trim()).filter(Boolean), enabled: form.enabled, frequency_hours: 24, priority: 50 }, form.id || undefined), "Source saved."); }
  return <><PageTitle title="Affiliate sources" description="Sync only administrator-approved official URLs; inspect imported facts before approving them for generation." />
    <form onSubmit={submit} className="mb-7 grid gap-3 rounded-lg border bg-background p-4 sm:grid-cols-2"><h2 className="sm:col-span-2 font-semibold">{form.id ? "Edit source" : "Add source"}</h2><label>Brand ID<input className="w-full rounded border p-2" type="number" min="1" required value={form.brand_id} onChange={e => setForm({ ...form, brand_id: e.target.value })} /></label><label>Name<input className="w-full rounded border p-2" required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label>Type<select className="w-full rounded border p-2" value={form.type} onChange={e => setForm({ ...form, type: e.target.value })}>{types.map(x => <option key={x}>{x}</option>)}</select></label><label>Official HTTPS URL<input className="w-full rounded border p-2" type="url" value={form.url} onChange={e => setForm({ ...form, url: e.target.value })} /></label><label>Allowed domains (comma separated)<input className="w-full rounded border p-2" value={form.allowed_domains} onChange={e => setForm({ ...form, allowed_domains: e.target.value })} placeholder="elevenlabs.io, elevenlabs.com" /></label><label>Notes / manually approved facts<textarea className="w-full rounded border p-2" value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })} /></label><label className="flex items-center gap-2"><input type="checkbox" checked={form.enabled} onChange={e => setForm({ ...form, enabled: e.target.checked })} />Enabled</label><div><button className="rounded bg-primary px-4 py-2 text-primary-foreground" type="submit">Save source</button></div></form>
    {q.isPending && <p>Loading sources…</p>}{q.isError && <p role="alert">Could not load sources.</p>}
    <div className="space-y-4">{q.data?.map(s => <article key={s.id} className="rounded-lg border bg-background p-4"><h2 className="font-semibold">{s.name} · {s.type} · {s.status}</h2><p className="break-all text-sm">{s.url || "Manual notes / import"} · last sync {s.last_synced_at ? new Date(s.last_synced_at).toLocaleString() : "Never"} · next sync {s.next_sync_at ? new Date(s.next_sync_at).toLocaleString() : "Not scheduled"}</p>{s.last_error && <p className="text-destructive">{s.last_error}</p>}<div className="my-3 flex gap-3 text-sm"><button className="underline" onClick={() => edit(s)}>Edit</button>{!(["MANUAL", "CSV_IMPORT", "WEBHOOK"].includes(s.type)) && <button className="underline" onClick={() => void run(() => sourceAction(s.id, "test"), "Source host validated.")}>Test</button>}{!["CSV_IMPORT", "WEBHOOK"].includes(s.type) && <button className="underline" onClick={() => void run(() => sourceAction(s.id, "sync"), "Sync queued.")}>Sync Now</button>}<button className="underline" onClick={() => void run(() => saveSource({ brand_id: s.brand_id, name: s.name, type: s.type, url: s.url, allowed_domains: s.allowed_domains, notes: s.notes, enabled: !s.enabled }, s.id), "Source updated.")}>{s.enabled ? "Disable" : "Enable"}</button></div>{s.type === "CSV_IMPORT" && <label className="text-sm">Import CSV with title,body,source_url columns <input type="file" accept=".csv,text/csv" onChange={e => { const file = e.target.files?.[0]; if (file) void run(() => importSourceCsv(s.id, file), "CSV imported for review."); }} /></label>}{s.documents.map(d => <div key={d.id} className="mt-3 rounded border p-3 text-sm"><p>{d.title} · {d.status} · {d.synced_at}</p><p className="break-all">{d.source_url}</p><details><summary>View imported text</summary><pre className="max-h-60 overflow-auto whitespace-pre-wrap">{d.body}</pre></details>{d.status === "PENDING" && <button className="mt-2 underline" onClick={() => void run(() => approveSourceDocument(d.id), "Source knowledge approved.")}>Approve factual source</button>}</div>)}</article>)}</div>
  </>;
}
