"use client";
import { useState, type FormEvent } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import PageTitle from "@/components/admin/page-title";
import { Button } from "@/components/ui/button";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { apiErrorMessage } from "@/lib/api-error";
import { agentContent, contentAction, reviseContent, setContentLocks, savePreference, downloadMetadata, downloadAsset, confirmPublication } from "@/services/affiliate-agent";
import { components, platforms, type AgentContent, type Platform, type Snapshot, type Version } from "@/types/affiliate-agent";
import { getSocialAccounts } from "@/services/agent-setup";

const selectClass = "w-full rounded-lg border bg-background p-2 text-sm";
const pretty = (value: unknown) => typeof value === "string" ? value : JSON.stringify(value, null, 2);

export default function ReviewDetail({ id }: { id: number }) {
  const client = useQueryClient(); const [selectedId, setSelectedId] = useState<number | null>(null); const [busy, setBusy] = useState(false);
  const q = useQuery({ queryKey: ["agent-content", id], queryFn: () => agentContent(id), refetchInterval: query => ["GENERATING", "REVISION_PENDING"].includes(query.state.data?.status || "") || query.state.data?.publications.some(p => p.status === "SCHEDULED") ? 3000 : false });
  const refresh = () => Promise.all([client.invalidateQueries({ queryKey: ["agent-content", id] }), client.invalidateQueries({ queryKey: ["agent-contents"] }), client.invalidateQueries({ queryKey: ["agent-overview"] })]);
  async function run(action: () => Promise<unknown>, message: string) {
    setBusy(true); try { await action(); toast.success(message); await refresh(); } catch (error) { toast.error(apiErrorMessage(error, error instanceof Error ? error.message : "Action failed.")); } finally { setBusy(false); }
  }
  if (q.isPending) return <p>Loading content…</p>;
  if (q.isError || !q.data) return <div role="alert"><p>Could not load this content.</p><Button className="mt-3" onClick={() => q.refetch()}>Retry</Button></div>;
  const c = q.data; const current = c.versions.find(v => v.id === c.current_version_id); const viewed = c.versions.find(v => v.id === selectedId) || current;
  const pending = c.status === "REVISION_PENDING"; const historical = viewed?.id !== current?.id; const disabled = busy || pending || historical;
  return <><PageTitle title={c.title} description={`${c.brand?.name || "Generic brand"} · ${c.product?.name || "No product"} · ${c.status}`} />
    <div className="mb-6 rounded-xl border bg-background p-4"><p className="font-medium">{c.status === "FINAL_APPROVED" ? `Version ${current?.number} is FINAL_APPROVED.` : "Publication requires final approval of the current version."}</p>{pending && <p className="mt-2" role="status">Revision in progress. The result will return to this review queue.</p>}{c.status === "GENERATING" && <p className="mt-2" role="status">Generating the voice and master video. This page will refresh automatically.</p>}{c.status === "GENERATION_FAILED" && <p className="mt-2 text-destructive" role="alert">Generation failed. Check provider configuration and worker logs, then retry the failed Laravel job.</p>}</div>
    {viewed && current && <><div className="mb-5 flex flex-wrap items-center gap-3"><label className="text-sm font-medium" htmlFor="view-version">Preview version</label><select id="view-version" className={`${selectClass} max-w-xs`} value={viewed.id} onChange={e => setSelectedId(Number(e.target.value))}>{c.versions.map(v => <option key={v.id} value={v.id}>Version {v.number}{v.id === current.id ? " · current" : " · historical"}{v.mock ? " · mock" : ""}</option>)}</select>{historical && <><span className="text-sm text-muted-foreground">Historical preview; actions apply after returning to the current version.</span><Button variant="outline" onClick={() => setSelectedId(current.id)}>Return to current</Button><Button disabled={busy || pending} variant="secondary" onClick={() => run(() => contentAction(id, "restore", current.id, { source_version_id: viewed.id }), "Restored as a new version for review.")}>Restore this version</Button></>}</div>
      <div className="grid items-start gap-6 lg:grid-cols-[minmax(260px,380px)_1fr]">
        <Card><CardHeader><CardTitle>Master video · v{viewed.number}</CardTitle></CardHeader><CardContent className="space-y-4"><video key={viewed.assets.video.url} aria-label={`Master video version ${viewed.number}`} className="aspect-[9/16] max-h-[650px] w-full rounded-lg bg-black" controls preload="metadata" src={viewed.assets.video.url} /><label className="block font-medium">Voiceover</label><audio aria-label="Voiceover preview" className="w-full" controls preload="metadata" src={viewed.assets.voice.url} />{viewed.mock && <p className="rounded-lg bg-amber-100 p-3 text-amber-950">MOCK PREVIEW: the audio is a test tone, not generated narration.</p>}<p className="text-xs text-muted-foreground">Preview links expire after 30 minutes. Refresh this page if playback stops.</p></CardContent></Card>
        <div className="space-y-5"><Preview version={viewed} />
          <Card><CardHeader><CardTitle>QA checks</CardTitle></CardHeader><CardContent><div className="flex flex-wrap gap-2">{Object.entries(viewed.qa.checks).map(([name, passed]) => <span key={name} className={`rounded-md px-2 py-1 text-xs ${passed ? "bg-emerald-100 text-emerald-900" : "bg-red-100 text-red-900"}`}>{name}: {passed ? "PASS" : "FAIL"}</span>)}</div><p className="mt-3 text-sm text-muted-foreground">{viewed.qa.review_required}</p></CardContent></Card>
          <Card><CardHeader><CardTitle>Research sources</CardTitle></CardHeader><CardContent className="space-y-2 text-sm">{viewed.references?.length ? viewed.references.map((ref, i) => <details className="rounded border p-2" key={i}><summary className="break-all">{ref.source_url || "Approved manual note"} · synced {new Date(ref.synced_at).toLocaleString()}</summary><p className="mt-2 whitespace-pre-wrap">{ref.facts}</p></details>) : <p>No approved source references were attached to this version.</p>}</CardContent></Card>
        </div>
      </div>
      {!historical && <div className="mt-6 grid gap-6 xl:grid-cols-2"><FeedbackForm key={`feedback-${current.id}`} content={c} version={current} disabled={disabled} run={run} /><Card><CardHeader><CardTitle>Component locks</CardTitle></CardHeader><CardContent><p className="mb-3 text-muted-foreground">Locked components are preserved. Lock changes invalidate approval. Dependent generation stops if it would alter a locked voice or video.</p><div className="grid gap-2 sm:grid-cols-2">{[...components, ...current.snapshot.scenes.map(s => `scenes.${s.id}`), ...platforms.map(p => `metadata.${p}`)].map(lock => <label key={lock} className="flex items-center gap-2 rounded-md border p-2"><input type="checkbox" checked={c.locks.includes(lock)} disabled={busy || pending} onChange={() => run(() => setContentLocks(id, current.id, c.locks.includes(lock) ? c.locks.filter(l => l !== lock) : [...c.locks, lock]), "Locks updated; approval invalidated.")} />{lock}</label>)}</div></CardContent></Card><EditForm key={`edit-${current.id}`} version={current} contentId={id} disabled={disabled} run={run} />
        <Card><CardHeader><CardTitle>Final review</CardTitle></CardHeader><CardContent className="space-y-4"><p>Approve only after watching the master video, listening to the voiceover and checking the script, scenes, captions, CTA, disclosure and every platform’s metadata.</p><p className="text-sm text-muted-foreground">Any accepted edit creates a new version and invalidates approval. A restored version also requires a new approval.</p><div className="flex flex-wrap gap-3"><Button disabled={disabled || !current.qa.passed || !["REVIEW_PENDING", "FINAL_APPROVED"].includes(c.status)} onClick={() => run(() => contentAction(id, "approve", current.id), `Version ${current.number} FINAL_APPROVED.`)}>{c.status === "FINAL_APPROVED" ? "Final approved" : `Final approve v${current.number}`}</Button><Button disabled={disabled} variant="destructive" onClick={() => { const reason = window.prompt("Reason for rejection"); if (reason?.trim()) void run(() => contentAction(id, "reject", current.id, { reason }), "Content rejected."); }}>Reject with reason</Button></div></CardContent></Card></div>}
      <Card className="mt-6"><CardHeader><CardTitle>Version history & before/after changes</CardTitle></CardHeader><CardContent className="space-y-4">{c.versions.map(v => <details key={v.id} className="rounded-lg border p-4" open={v.id === viewed.id}><summary className="cursor-pointer font-medium">Version {v.number} · {new Date(v.created_at).toLocaleString()} · {v.steps.join(" → ")}{v.restored_from_id ? ` · restored from version ID ${v.restored_from_id}` : ""}</summary><p className="my-2 break-all font-mono text-xs text-muted-foreground">Manifest: {v.snapshot_hash}</p>{!v.changes.length && <p>Initial generated version.</p>}{v.changes.map((change, i) => <div key={i} className="mt-3"><h4 className="font-medium">{change.component}</h4><div className="mt-2 grid gap-3 md:grid-cols-2"><div><p className="text-xs text-muted-foreground">Before</p><pre className="max-h-48 overflow-auto whitespace-pre-wrap rounded-lg bg-muted p-3 text-xs">{pretty(change.before)}</pre></div><div><p className="text-xs text-muted-foreground">After</p><pre className="max-h-48 overflow-auto whitespace-pre-wrap rounded-lg bg-muted p-3 text-xs">{pretty(change.after)}</pre></div></div></div>)}</details>)}</CardContent></Card>
      <Card className="mt-6"><CardHeader><CardTitle>Feedback & approval audit</CardTitle></CardHeader><CardContent className="space-y-3">{c.feedback.map(f => <div className="rounded-lg border p-3" key={f.id}><p className="font-medium">{f.target} · {f.status}</p><p className="mt-1 whitespace-pre-wrap">{f.feedback}</p>{f.error && <p role="alert" className="mt-2 text-destructive">{f.error}</p>}<p className="mt-1 text-xs text-muted-foreground">Base version ID {f.base_version_id}{f.result_version_id ? ` → version ID ${f.result_version_id}` : ""}</p></div>)}{c.approvals.map(a => <p className="text-sm" key={a.id}>Version ID {a.version_id} approved by admin #{a.approved_by} on {new Date(a.approved_at).toLocaleString()}{a.invalidated_at ? ` · invalidated ${new Date(a.invalidated_at).toLocaleString()}` : " · valid"}</p>)}</CardContent></Card>
      {!historical && <Publishing content={c} version={current} disabled={busy || pending} run={run} />}
    </>}
  </>;
}

type Run = (action: () => Promise<unknown>, message: string) => Promise<void>;
function Preview({ version }: { version: Version }) {
  const s = version.snapshot;
  return <><Card><CardHeader><CardTitle>Script & captions</CardTitle></CardHeader><CardContent className="space-y-4"><div><h3 className="font-medium">Spoken script</h3><p className="mt-2 whitespace-pre-wrap">{s.script}</p></div><div><h3 className="font-medium">Captions</h3><p className="mt-2 whitespace-pre-wrap">{s.captions}</p></div></CardContent></Card><Card><CardHeader><CardTitle>Scenes · {s.scenes.reduce((n, scene) => n + scene.duration, 0)} seconds</CardTitle></CardHeader><CardContent className="space-y-3">{s.scenes.map((scene, i) => <div key={scene.id} className="rounded-lg border p-3"><p className="font-medium">{i + 1}. {scene.id} · {scene.duration}s</p><p className="mt-1">{scene.text}</p><p className="mt-1 text-xs text-muted-foreground">{scene.media_id ? `Media #${scene.media_id}` : "Solid background"}</p></div>)}</CardContent></Card><Card><CardHeader><CardTitle>CTA & affiliate disclosure</CardTitle></CardHeader><CardContent><p>{s.cta}</p><p className="mt-3 rounded-lg bg-muted p-3">{s.disclosure}</p></CardContent></Card><Card><CardHeader><CardTitle>Platform metadata</CardTitle></CardHeader><CardContent className="space-y-3">{platforms.map(p => <details className="rounded-lg border p-3" key={p}><summary className="cursor-pointer font-medium capitalize">{p}</summary><dl className="mt-3 space-y-3">{Object.entries(s.metadata[p]).map(([key, val]) => <div key={key}><dt className="text-xs uppercase text-muted-foreground">{key.replaceAll("_", " ")}</dt><dd className="break-words whitespace-pre-wrap">{Array.isArray(val) ? val.join(" ") : val}</dd></div>)}</dl><Button className="mt-4" variant="outline" onClick={async () => { try { await navigator.clipboard.writeText(`${s.metadata[p].title}\n\n${s.metadata[p].caption}\n\n${s.metadata[p].description}\n\n${s.metadata[p].hashtags.join(" ")}\n${s.metadata[p].cta}\n${s.metadata[p].affiliate_url}\n${s.metadata[p].disclosure}`); toast.success("Metadata copied."); } catch { toast.error("Clipboard permission is unavailable."); } }}>Copy {p} metadata</Button></details>)}</CardContent></Card></>;
}
function FeedbackForm({ content, version, disabled, run }: { content: AgentContent; version: Version; disabled: boolean; run: Run }) {
  const [feedback, setFeedback] = useState(""); const [target, setTarget] = useState("all"); const [future, setFuture] = useState(false); const [scope, setScope] = useState<"global" | "brand" | "product">(content.brand_id ? "brand" : "global");
  const [instruction, setInstruction] = useState("");
  async function submit(e: FormEvent) {
    e.preventDefault();
    await run(async () => {
      const result = await reviseContent(content.id, version.id, feedback, target);
      if (future) {
        try { await savePreference({ scope, brand_id: content.brand_id, affiliate_product_id: content.affiliate_product_id, component: target.split(".")[0], instruction: instruction || feedback, enabled: true, source_feedback_id: result.id }); }
        catch (err) { toast.error(`Revision queued, but preference was not saved: ${apiErrorMessage(err)}`); }
      }
      setFeedback("");
    }, "Revision queued for another review.");
  }
  return <Card><CardHeader><CardTitle>Request a revision</CardTitle></CardHeader><CardContent><form className="space-y-4" onSubmit={submit}><label className="block text-sm">Feedback target<select className={`${selectClass} mt-2`} value={target} onChange={e => setTarget(e.target.value)}><option value="all">Entire content</option>{components.filter(x => x !== "video").map(x => <option key={x}>{x}</option>)}{version.snapshot.scenes.map(s => <option key={s.id} value={`scenes.${s.id}`}>Scene: {s.id}</option>)}{platforms.map(p => <option key={p} value={`metadata.${p}`}>Metadata: {p}</option>)}</select></label><label className="block text-sm">Natural-language feedback<Textarea className="mt-2 min-h-28" value={feedback} onChange={e => setFeedback(e.target.value)} placeholder="Make the opening more direct. Keep the voice and closing scene unchanged." required maxLength={6000} /></label><label className="flex items-center gap-2"><input type="checkbox" checked={future} onChange={e => setFuture(e.target.checked)} />Apply this preference to future content</label>{future && <div className="space-y-3 rounded-lg border p-3"><p className="text-xs text-muted-foreground">Saved as an explicit preference for future generation. Existing unrelated content remains unchanged.</p><label className="block text-sm">Preference scope<select className={`${selectClass} mt-2`} value={scope} onChange={e => setScope(e.target.value as typeof scope)}><option value="global">All future content</option>{content.brand_id && <option value="brand">This brand</option>}{content.affiliate_product_id && <option value="product">This product</option>}</select></label><label className="block text-sm">Reusable preference<Textarea className="mt-2" value={instruction} onChange={e => setInstruction(e.target.value)} placeholder="Use short, direct openings for future tutorials." required maxLength={6000} /></label></div>}<Button type="submit" disabled={disabled || !feedback.trim()}>Request revision of v{version.number}</Button></form></CardContent></Card>;
}
function EditForm({ version, contentId, disabled, run }: { version: Version; contentId: number; disabled: boolean; run: Run }) {
  const [component, setComponent] = useState<keyof Snapshot>("script"); const [value, setValue] = useState(version.snapshot.script);
  async function submit(e: FormEvent) {
    e.preventDefault();
    let parsed: unknown = value;
    if (["scenes", "metadata", "voice"].includes(component)) { try { parsed = JSON.parse(value); } catch { toast.error("Enter valid JSON for this component."); return; } }
    await run(() => reviseContent(contentId, version.id, `Admin directly edited ${component}.`, component, { [component]: parsed } as Partial<Snapshot>), "Edit queued as a new immutable version.");
  }
  return <Card><CardHeader><CardTitle>Edit a component</CardTitle></CardHeader><CardContent><form className="space-y-4" onSubmit={submit}><label className="block text-sm">Component<select className={`${selectClass} mt-2`} value={component} onChange={e => { const next = e.target.value as keyof Snapshot; setComponent(next); setValue(pretty(version.snapshot[next])); }}>{components.filter(x => x !== "video").map(x => <option key={x}>{x}</option>)}</select></label><Textarea aria-label="Component replacement" className="min-h-40 font-mono text-sm" value={value} onChange={e => setValue(e.target.value)} required /><p className="text-xs text-muted-foreground">Scenes, platform metadata and voice settings use JSON. Only affected generation steps rerun. Script edits also update captions and narration.</p><Button type="submit" variant="outline" disabled={disabled}>Save as a new version</Button></form></CardContent></Card>;
}
function Publishing({ content, version, disabled, run }: { content: AgentContent; version: Version; disabled: boolean; run: Run }) {
  const [platform, setPlatform] = useState<Platform>("pinterest"); const [mode, setMode] = useState("manual"); const [date, setDate] = useState(""); const [accountId, setAccountId] = useState(0);
  const accounts = useQuery({ queryKey: ["agent-social"], queryFn: getSocialAccounts });
  const eligible = accounts.data?.accounts.filter(a => a.platform === platform && a.status === "CONNECTED" && a.publishing_enabled) || [];
  const approved = content.status === "FINAL_APPROVED" && content.final_approved_version_id === version.id;
  return <Card className="mt-6"><CardHeader><CardTitle>Publishing & manual export · v{version.number}</CardTitle></CardHeader><CardContent className="space-y-4">
    <p className="text-sm text-muted-foreground">The approved master video is shared across five independent platform records. Connected API accounts require production readiness; manual export is always available.</p>
    <div className="flex flex-wrap gap-3"><Button disabled={!approved || disabled} variant="outline" onClick={() => run(() => downloadAsset(version.assets.video.url, `content-${content.id}-v${version.number}.mp4`), "Master video downloaded.")}>Download master video</Button><Button disabled={!approved || disabled} variant="outline" onClick={() => run(() => downloadMetadata(content.id, version.id, version.number), "Platform metadata exported.")}>Export metadata</Button>{platforms.map(p => <Button key={p} disabled={!approved || disabled} variant="outline" onClick={() => run(() => navigator.clipboard.writeText(`${version.snapshot.metadata[p].title}\n${version.snapshot.metadata[p].caption}\n${version.snapshot.metadata[p].description}\n${version.snapshot.metadata[p].affiliate_url}\n${version.snapshot.metadata[p].disclosure}`), `${p} metadata copied.`)}>Copy {p}</Button>)}</div>
    <form className="flex flex-wrap items-end gap-3" onSubmit={e => { e.preventDefault(); void run(() => contentAction(content.id, "publications", version.id, { platform, mode, ...(mode === "api" ? { social_account_id: accountId } : {}), ...(date ? { scheduled_at: new Date(date).toISOString() } : {}) }), "Publication record scheduled."); }}>
      <label className="text-sm">Platform<select className={`${selectClass} mt-1`} value={platform} onChange={e => { setPlatform(e.target.value as Platform); setAccountId(0); }}>{platforms.map(p => <option key={p}>{p}</option>)}</select></label>
      <label className="text-sm">Mode<select className={`${selectClass} mt-1`} value={mode} onChange={e => setMode(e.target.value)}><option value="manual">Manual export</option><option value="api">Connected API</option><option value="mock">Mock test</option></select></label>
      {mode === "api" && <label className="text-sm">Account<select className={`${selectClass} mt-1`} value={accountId} onChange={e => setAccountId(Number(e.target.value))}><option value={0}>Select account</option>{eligible.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label>}
      <label className="text-sm">Schedule (your local time)<Input className="mt-1" type="datetime-local" value={date} onChange={e => setDate(e.target.value)} /></label><Button type="submit" disabled={!approved || disabled || (mode === "api" && (!accountId || version.mock))}>Schedule exact v{version.number}</Button>
    </form>
    <div className="space-y-3">{content.publications.map(p => <div key={p.id} className="rounded-lg border p-3"><p className="font-medium">{p.platform} · {p.status} · version ID {p.version_id}</p><p className="text-sm">{new Date(p.scheduled_at).toLocaleString()}</p>{p.error && <p className="text-destructive">{p.error}</p>}{p.platform_url && <a className="break-all text-sm underline" href={p.platform_url} target="_blank" rel="noreferrer">View post</a>}{p.external_id && <p className="break-all text-sm">{p.external_id}</p>}{p.status === "EXPORT_READY" && <Button className="mt-3" disabled={!approved || disabled} variant="outline" onClick={() => { const url = window.prompt("Paste the published post URL to record your manual publication"); if (url) void run(() => confirmPublication(p.id, url), "Manual publication recorded."); }}>Confirm manual publication</Button>}</div>)}</div>
  </CardContent></Card>;
}
